version: '3.8'
services:
    app:
        build: .
        ports:
            - 8081:8080
        restart: unless-stopped
    # frontend:
    #     build:
    #         context: .
    #         dockerfile: ./frontend/Dockerfile
    # backend:
    #     build:
    #         context: .
    #         dockerfile: ./backend/Dockerfile
    #     ports:
    #         - 8081:8080
    #     depends_on:
    #         - frontend
    # db:
    #     image: postgres
    #     restart: always
    #     environment:
    #         - POSTGRES_HOST_AUTH_METHOD=trust


